spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: localhost:3306/postgres
    password: postgres

  rabbitmq:
    port: '5672'
    host: rabbitmq-container

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: '8086'

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
